// <auto-generated />
namespace Konto.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tcs_decimal_bill_acc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tcs_decimal_bill_acc));
        
        string IMigrationMetadata.Id
        {
            get { return "202010030447454_tcs_decimal_bill_acc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
