// <auto-generated />
namespace Konto.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_salerate_billtrans : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_salerate_billtrans));
        
        string IMigrationMetadata.Id
        {
            get { return "202012020803128_added_salerate_billtrans"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
