// <auto-generated />
namespace Konto.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_postion_packtype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_postion_packtype));
        
        string IMigrationMetadata.Id
        {
            get { return "202011171228408_added_postion_packtype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
