// <auto-generated />
namespace Konto.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class sp_lookup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sp_lookup));
        
        string IMigrationMetadata.Id
        {
            get { return "202005290522277_sp_lookup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
