// <auto-generated />
namespace Konto.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class billmain_Addless : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(billmain_Addless));
        
        string IMigrationMetadata.Id
        {
            get { return "202008121328227_billmain_Addless"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
