// <auto-generated />
namespace Konto.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class prod_out_lotNo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(prod_out_lotNo));
        
        string IMigrationMetadata.Id
        {
            get { return "202009040828283_prod_out_lotNo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
