// <auto-generated />
namespace Konto.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_user_Webapi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_user_Webapi));
        
        string IMigrationMetadata.Id
        {
            get { return "202010211507462_added_user_Webapi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
