// <auto-generated />
namespace Konto.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class alter_prod_emp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_prod_emp));
        
        string IMigrationMetadata.Id
        {
            get { return "202102270618343_alter_prod_emp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
