// <auto-generated />
namespace Konto.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class accid_challan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(accid_challan));
        
        string IMigrationMetadata.Id
        {
            get { return "202103181320422_accid_challan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
