// <auto-generated />
namespace Konto.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_tcs_challan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_tcs_challan));
        
        string IMigrationMetadata.Id
        {
            get { return "202101221144341_added_tcs_challan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
