CREATE TABLE [dbo].[Acc]
(
	[Id] INT IDENTITY NOT NULL ,
	[AccName] VARCHAR(100),
	[PrintName] VARCHAR(100),
	[GroupId] INT DEFAULT 1, 
    [PGroupId] INT NULL DEFAULT 1,
	[TdsReq] VARCHAR (3) NULL,
	[TcsReq] VARCHAR (3) NULL,
	[VatTds] VARCHAR(5) NULL,
	[IoTax] VARCHAR (6),
	[DeducteeId] INT NULL DEFAULT 1,
	[NopId] INT NULL DEFAULT 1,
	[CrDays] INT, 
    [CrLimit] NUMERIC(18, 2) NULL,
    [BToB] VARCHAR(3) NULL,
    [AgentId] INT NULL DEFAULT 1, 
    [TransportId] INT NULL DEFAULT 1,
	[EmpId] INT NULL DEFAULT 1,
    [AadharNo] VARCHAR(12) NULL,
    [GstIn] VARCHAR(15) NULL,
	[GSTDate] datetime null,
    [PanNo] VARCHAR(10) NULL,
	[Extra1] VARCHAR(MAX) NULL, 
    [Extra2] VARCHAR(50) NULL,
	[IsActive] BIT NOT NULL DEFAULT 1, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [CreateDate] DATETIME2 NULL, 
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL, 
    [RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(), 
    [AddressId] INT NULL, 
    [Grade] VARCHAR(2) NULL, 
    [CollDay] VARCHAR(25) NULL, 
    [CollById] INT NULL, 
    CONSTRAINT [PK_Acc] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_Acc_Id] UNIQUE CLUSTERED ([Id]), 
    CONSTRAINT [FK_Acc_Nop] FOREIGN KEY (NopId) REFERENCES [Nop]([Id]) on delete set default, 
    CONSTRAINT [FK_Acc_Deductee] FOREIGN KEY ([DeducteeId]) REFERENCES [Deductee]([Id]) on delete set default, 
    CONSTRAINT [FK_Acc_AcGroup] FOREIGN KEY ([GroupId]) REFERENCES [AcGroup]([Id]), 
    CONSTRAINT [FK_Acc_PartyGroup] FOREIGN KEY ([PGroupId]) REFERENCES [PartyGroup]([Id]) on delete set default, 
	CONSTRAINT [FK_Acc_Emp] FOREIGN KEY ([EmpId]) REFERENCES [Emp]([Id]) on delete set default, 
)
