CREATE TABLE [dbo].[AccAddress]
(
	[Id] INT IDENTITY NOT NULL ,
	[AccId] INT,
	[Address1] VARCHAR(200), 
    [Address2] VARCHAR(200) NULL, 
    [CityId] INT NULL DEFAULT 1, 
    [AreaId] INT NULL DEFAULT 1, 
    [PinCode] VARCHAR(15) NULL, 
    [ContactPerson] VARCHAR(75) NULL, 
    [MobileNo] VARCHAR(15) NULL, 
    [Phone] VARCHAR(50) NULL, 
    [Email] VARCHAR(200) NULL, 
    [Website] VARCHAR(50) NULL, 
    [RouteId] INT NULL DEFAULT 1, 
    [IsDefault] BIT NULL, 
    [IsDeleted] BIT NULL, 
	[RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(), 
    [AddressType] VARCHAR(25) NULL, 
    [Others] VARCHAR(100) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    CONSTRAINT [PK_AccAddress] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_AccAddress_Id] UNIQUE CLUSTERED ([Id]), 
    CONSTRAINT [FK_AccAddress_Acc] FOREIGN KEY ([AccId]) REFERENCES [Acc]([Id]) ON DELETE CASCADE, 
    CONSTRAINT [FK_AccAddress_Route] FOREIGN KEY ([RouteId]) REFERENCES [Route]([Id]) on delete set default,
	CONSTRAINT [FK_AccAddress_City] FOREIGN KEY ([CityId]) REFERENCES [City]([Id]) on delete set default,
	CONSTRAINT [FK_AccAddress_Area] FOREIGN KEY ([AreaId]) REFERENCES [Area]([Id]) on delete set default,

)
