CREATE TABLE [dbo].[AccOther]
(
	[Id] INT IDENTITY NOT NULL ,
	[AccId] INT,
	[OpStockAccId] INT DEFAULT 1,
	[IntAccId] INT DEFAULT 1,
    [IntTdsAccId] INT DEFAULT 1,
    [IntPer] NUMERIC (6, 2),
    [IntTdsPer] NUMERIC (6, 2),
    [TdsDrCr] VARCHAR (2),
	[TcsAccId] INT DEFAULT 1,
    [TcsPer] NUMERIC (6, 2),
	[TdsAccId] INT DEFAULT 1,
    [TdsPer] NUMERIC (6, 2),
	[DepAccId] INT DEFAULT 1,
    [DepPer] NUMERIC (6, 2),
	[RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(), 
    [IsDeleted] BIT NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    CONSTRAINT [PK_AcOther] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_AccOther_Id] UNIQUE CLUSTERED ([Id]), 
	CONSTRAINT [FK_AccOther_Acc] FOREIGN KEY ([AccId]) REFERENCES [Acc]([Id]) ON DELETE CASCADE, 
	CONSTRAINT [FK_AccOther_OpStcok_Acc] FOREIGN KEY ([OpStockAccId]) REFERENCES [Acc]([Id]), 
	CONSTRAINT [FK_AccOther_Int_Acc] FOREIGN KEY ([IntAccId]) REFERENCES [Acc]([Id]),
	CONSTRAINT [FK_AccOther_IntTds_Acc] FOREIGN KEY ([IntTdsAccId]) REFERENCES [Acc]([Id]) , 
	CONSTRAINT [FK_AccOther_Tds_Acc] FOREIGN KEY ([TdsAccId]) REFERENCES [Acc]([Id]) , 
	CONSTRAINT [FK_AccOther_Tcs_Acc] FOREIGN KEY ([TcsAccId]) REFERENCES [Acc]([Id]) , 
	CONSTRAINT [FK_AccOther_Dep_Acc] FOREIGN KEY ([DepAccId]) REFERENCES [Acc]([Id]) , 
)
