CREATE TABLE [dbo].[AcGroup]
(
	[Id] INT IDENTITY NOT NULL , 
    [GroupCode] VARCHAR(15) NULL, 
    [GroupName] VARCHAR(50) NULL, 
    [UnderGroupId] INT NULL, 
	[OppSideName] VARCHAR(50) NULL,
    [Nature] VARCHAR(30) NULL, 
    [Remark] VARCHAR(MAX) NULL, 
    [BlSort] INT NULL, 
    [TbSort] INT NULL, 
    [TrSort] INT NULL, 
    [OnlyTotal] BIT NULL ,
	[OpBalanceReq] BIT NULL,
    [AgentReq]           BIT               NULL,
    [TransportReq]       BIT                NULL,
    [AddressReq]         BIT                NULL,
    [TaxationReq]        BIT                NULL,
    [SalesmanReq]        BIT                NULL,
    [BankDetailReq]      BIT                NULL,
    [PartyGroupReq]      BIT                NULL,
    [PriceLevelReq]      BIT                NULL,
    [CollDaysReq]        BIT                NULL,
    [IntAccountReq] BIT                     NULL,
    [DeprAccountReq]     BIT                NULL,
    [TcsReq]        BIT                NULL,
    [TdsReq]        BIT                NULL,
    [TaxTypeReq]    BIT                NULL,
    [CrLimitReq]    BIT                NULL,
	[GradeReq] BIT NULL,
	[Extra1] VARCHAR(50) NULL, 
    [Extra2] VARCHAR(50) NULL,
	[IsActive] BIT NOT NULL DEFAULT 1, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [CreateDate] DATETIME2 NULL, 
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL, 
    [RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(), 
    CONSTRAINT [PK_AcGroup] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_Acgroup_Id] UNIQUE CLUSTERED ([Id]), 
)
