CREATE TABLE [dbo].[Branch]
(
	[Id] INT IDENTITY NOT NULL , 
	[BranchCode] VARCHAR(10) NULL,
    [BranchName] VARCHAR(75) NULL, 
	[CompId]	INT	NULL,
    [Address1] VARCHAR(100) NULL, 
    [Address2] VARCHAR(100) NULL,
	[CityId] Int NULL,
	[AreaId] INT NULL,
	[PinCode] varchar(10) NULL,
	[GstIn] VARCHAR(25) NULL,
	[AadharNo] VARCHAR(25) NULL,
    [ContactPerson] VARCHAR(50) NULL, 
    [MobileNo] VARCHAR(50) NULL,
	[Remark] VARCHAR(200),
	[Extra1] VARCHAR(50),
	[Extra2] VARCHAR(50),
	[IsActive] BIT NOT NULL DEFAULT 1, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [CreateDate] DATETIME2 NULL, 
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL, 
    [RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(), 
    CONSTRAINT [PK_Branch] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_Branch_Id] UNIQUE CLUSTERED ([Id]), 
    CONSTRAINT [FK_Branch_Company] FOREIGN KEY ([CompId]) REFERENCES [Company]([Id]), 
    CONSTRAINT [FK_Branch_Area] FOREIGN KEY ([AreaId]) REFERENCES [Area]([Id]), 
	CONSTRAINT [FK_Branch_City] FOREIGN KEY ([CityId]) REFERENCES [City]([Id]), 
)
