CREATE TABLE [dbo].[EmailSmsLog]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RowId] [uniqueidentifier] NOT NULL,
	[TransType] [varchar](2) NULL,
	[EmailTo] [varchar](1000) NULL,
	[SmsTo] [varchar](200) NULL,
	[EmailSub] [varchar](200) NULL,
	[EmailBody] [varchar](max) NULL,
	[EmalHeader] [varchar](max) NULL,
	[EmailFooter] [varchar](max) NULL,
	[SmsMsg] [varchar](500) NULL,
	[ScheduleTime] [datetime2](7) NULL,
	[UserName] [varchar](50) NULL,
	[CompanyName] [varchar](100) NULL,
	[Sended] [bit] NOT NULL,
	[SendTime] [datetime2](7) NULL,
	[ResponseMsg] [varchar](max) NULL,
	[AttachFile] [varchar](1000) NULL,
	[FromMailId] [varchar](100) NULL,
	[FromMailPass] [varbinary](50) NULL,
	  CONSTRAINT [PK_EmailSmsLog] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_EmailSmsLog_Id] UNIQUE CLUSTERED ([Id]), 
)
