CREATE TABLE [dbo].[Emp]
(
	[Id] INT IDENTITY NOT NULL , 
    [EmpName] VARCHAR(50) NULL, 
    [Address1] VARCHAR(100) NULL, 
    [Address2] VARCHAR(100) NULL, 
    [MobileNo] VARCHAR(15) NULL, 
    [Email] VARCHAR(50) NULL, 
    [AadharNo] VARCHAR(15) NULL, 
    [PanNo] VARCHAR(15) NULL, 
    [Remark] VARCHAR(MAX) NULL,
	[IsActive] BIT NOT NULL DEFAULT 1, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [CreateDate] DATETIME2 NULL, 
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL, 
    [RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(), 
    [CompId] INT NULL DEFAULT 1, 
    CONSTRAINT [PK_Emp] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_Emp] UNIQUE CLUSTERED ([Id]), 
    CONSTRAINT [FK_Emp_Company] FOREIGN KEY ([CompId]) REFERENCES [Company]([Id]) on delete set default, 
)
