CREATE TABLE [dbo].[Product]
(
	[Id] INT IDENTITY NOT NULL , 
    [ProductName] VARCHAR(100) NULL, 
    [ProductDesc] VARCHAR(500) NULL, 
    [ProductCode] VARCHAR(25) NULL, 
    [BarCode] VARCHAR(25) NULL, 
    [HsnCode] VARCHAR(15) NULL, 
	[PurTaxId] INT NULL,
    [TaxId] INT NULL, 
    [PTypeId] INT NULL, 
    [GroupId] INT NULL, 
    [SubGroupId] INT NULL, 
    [SizeId] INT NULL, 
    [CategoryId] INT NULL, 
    [StyleId] INT NULL, 
    [ColorId] INT NULL, 
    [BrandId] INT NULL, 
    [UomId] INT NULL, 
    [PurUomId] INT NULL,
	[PurDisc] numeric(10,2) NOT NULL,
	[PurSpDisc] numeric(10,2) NOt NULL,
	[SaleDisc] numeric(10,2) NOT NULL,
	[SaleSpDisc] numeric(10,2) NOT NULL,
	[ActualCost] NUMERIC(18,2) NOT NULL,
    [StockReq] VARCHAR(5) NULL,
	[BatchReq] VARCHAR(5) NULL,
	[SerialReq] VARCHAR(5) NULL,
	[MinLevel] Numeric(18,4) NOT NULL,
	[MaxLevel] NUMERIC(18,4) NOT NULL,
	[Rol] NUMERIC(18,4) NOT NULL,
	[MinOrdQty] NUMERIC(18,4) NOT NULL,
	[MaxOrdQty] NUMERIC(18,4) NOT NULL,
	[LeadDays] INT NOT NULL,
	[CheckNegative] BIT NOT NULL,
	[Ingr] Varchar(500),
    [Remark] VARCHAR(MAX) NULL,
	[SaleRateTaxInc] BIT NOT NULL DEFAULT(0),
	[VendorId] INT NULL,
	[StockAcId] INT NULL,
	[Sales] BIT NOT NULL DEFAULT(0),
	[Purchase] BIT NOT NULL DEFAULT(0),
	[Inventory] BIT NOT NULL DEFAULT(0),
	[FixedAsset] BIT NOT NULL DEFAULT(0),
	[WorkOrder] BIT NOT NULL DEFAULT(0),
	[StdWt] NUMERIC(18,4),
	[Price1] NUMERIC(18,2),
	[Price2] NUMERIC(18,2),
	[ItemType] varchar(1),
	[DesignDate] int null,
	[AccId] int null,
	[PartyItemId] int null,
	[ParentItemId] int null,
	[FabricTopId] int null,
	[FabricBottomId] int null,
	[FabricDupattaId] int null,
	[CatalogId] int null,
	[IsActive] BIT NOT NULL DEFAULT 1, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [CreateDate] DATETIME2 NULL, 
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL, 
    [RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(), 
    CONSTRAINT [PK_Product] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_Product_Id] UNIQUE CLUSTERED ([Id]), 
    CONSTRAINT [FK_Product_Type] FOREIGN KEY ([PTypeId]) REFERENCES [ProductType]([Id]), 
    CONSTRAINT [FK_Product_Category] FOREIGN KEY ([CategoryId]) REFERENCES [PCategory]([Id]), 
    CONSTRAINT [FK_Product_Group] FOREIGN KEY ([GroupId]) REFERENCES [PGroup]([Id]), 
    CONSTRAINT [FK_Product_SubGroup] FOREIGN KEY ([SubGroupId]) REFERENCES [PSubGroup]([Id]), 
    CONSTRAINT [FK_Product_Size] FOREIGN KEY ([SizeId]) REFERENCES [PSize]([Id]), 
    CONSTRAINT [FK_Product_Color] FOREIGN KEY ([ColorId]) REFERENCES [Color]([Id]), 
    CONSTRAINT [FK_Product_Brand] FOREIGN KEY ([BrandId]) REFERENCES [Brand]([Id]), 
    CONSTRAINT [FK_Product_Uom] FOREIGN KEY ([UomId]) REFERENCES [Uom]([Id]), 
    CONSTRAINT [FK_Product_PuUom] FOREIGN KEY ([PurUomId]) REFERENCES [Uom]([Id]), 
    CONSTRAINT [FK_Product_Style] FOREIGN KEY ([StyleId]) REFERENCES [Style]([Id]), 
    CONSTRAINT [FK_Product_TaxMaster] FOREIGN KEY ([TaxId]) REFERENCES [TaxMaster]([Id]), 

)
