CREATE TABLE [dbo].[ProductPrice]
(
	[Id] INT IDENTITY NOT NULL , 
    [ProductId] INT NULL, 
    [BatchNo] VARCHAR(25) NULL, 
    [MfgDate] VARCHAR(10) NULL, 
    [ExpDate] VARCHAR(10) NULL, 
    [DealerPrice] NUMERIC(18, 2) NULL, 
    [SaleRate] NUMERIC(18, 2) NULL, 
    [Qty] NUMERIC(18, 2) NULL, 
    [Mrp] NUMERIC(18, 2) NULL, 
    [BranchId] INT NULL, 
    [IssueQty] NUMERIC(18, 2) NULL,
	[IsActive] BIT NOT NULL DEFAULT 1,
    [IsDeleted] BIT NOT NULL DEFAULT 0,
    [CreateDate] DATETIME2 NULL,
    [ModifyDate] DATETIME2 NULL,
    [CreateUser] VARCHAR(50) NULL,
    [ModifyUser] VARCHAR(50) NULL,
    [IpAddress] VARCHAR(100) NULL,
    [RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(), 
    CONSTRAINT [PK_ProductPrice] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_ProductPrice_Id] UNIQUE CLUSTERED ([Id]), 
    CONSTRAINT [FK_ProductPrice_Product] FOREIGN KEY ([ProductId]) REFERENCES [Product]([Id]) ON DELETE CASCADE, 
)
