CREATE TABLE [dbo].[ProductBal]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CompanyId] [int] NOT NULL,
	[YearId] [int] NOT NULL,
	[ProductId] [int] NOT NULL,
	[GodownId] [int] NOT NULL,
	[BranchId] [int] NOT NULL,
	[ItemCode] [uniqueidentifier]  NULL,
	[OpNos] [int] NOT NULL,
	[OpQty] [numeric](18, 4) NOT NULL,
	[IssueNo] [int] NOT NULL,
	[IssueQty] [numeric](18, 4) NOT NULL,
	[RcptNos] [int] NOT NULL,
	[RcptQty] [numeric](18, 4) NOT NULL,
	[BalNos] [int] NOT NULL,
	[BalQty] [numeric](18, 4) NOT NULL,
	[Rate] [numeric](18, 4) NOT NULL,
	[StockValue] [numeric](18, 4) NOT NULL,
	[LotNo] [varchar](50) NULL, 
	[DivId] int null,
	  [CreateDate] DATETIME2 NULL, 
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL, 
    [RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(),
	CONSTRAINT [PK_ProductBal] PRIMARY KEY NONCLUSTERED ([RowId]), 
	CONSTRAINT [AK_ProductBal_Id] UNIQUE CLUSTERED ([Id]), 
    CONSTRAINT [FK_ProductBal_CompanyId] FOREIGN KEY ([CompanyId]) REFERENCES [Company]([Id]),  
    CONSTRAINT [FK_ProductBal_Product] FOREIGN KEY ([ProductId]) REFERENCES [Product]([Id]),
)