CREATE TABLE [dbo].[TaxMaster]
(
	[Id] INT IDENTITY NOT NULL , 
    [TaxName] VARCHAR(50) NULL, 
    [TaxType] VARCHAR(25) NULL, 
    [Sgst] NUMERIC(10, 2) NULL, 
    [Cgst] NUMERIC(10, 2) NULL, 
    [Igst] NUMERIC(10, 2) NULL, 
    [CessType] VARCHAR(25) NULL, 
    [Cess] NUMERIC(10, 2) NULL, 
    [CessRate] NUMERIC(10, 2) NULL,
	[Remark] VARCHAR(100),
	[Extra1] VARCHAR(50) NULL, 
    [Extra2] VARCHAR(50) NULL,
	[IsActive] BIT NOT NULL DEFAULT 1, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [CreateDate] DATETIME2 NULL, 
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL, 
    [RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(), 
    CONSTRAINT [PK_TaxMaster] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_TaxMaster_Id] UNIQUE CLUSTERED ([Id]), 
)
