
CREATE TABLE [dbo].[TempField](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FieldName] [varchar](500) NULL,
 CONSTRAINT [PK_TempField] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]