CREATE TABLE [dbo].[VchSetup]
(
	[Id] INT IDENTITY NOT NULL, 
    [VoucherId] INT NULL, 
    [CompId] INT NULL, 
	[InvoiceHeading] Varchar(50),
    [VchWidth] INT NULL, 
    [PreFillZero] BIT NULL, 
    [StartFrom] INT NULL, 
    [Increment] INT NULL, 
    [Serial_Mask] VARCHAR(25) NULL, 
    [Max_Value] INT NULL, 
    [Last_Serial] INT NULL, 
    [FyReset] BIT NULL, 
    [PrintAfterSave] BIT NULL, 
    [EmailAfterSave] BIT NULL, 
    [SmsAfterSave] BIT NULL, 
    [BookFix] BIT NOT NULL, 
    [AccId] INT NULL,
	[Extra1] VARCHAR(100) NULL, 
    [Extra2] VARCHAR(50) NULL,
	[IsActive] BIT NOT NULL DEFAULT 1, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [CreateDate] DATETIME2 NULL, 
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL, 
    [RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(), 
    CONSTRAINT [PK_VchSetup] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_VchSetup_Id] UNIQUE CLUSTERED ([Id]), 
    CONSTRAINT [FK_VchSetup_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [Voucher]([Id]), 
    CONSTRAINT [FK_VchSetup_Company] FOREIGN KEY ([CompId]) REFERENCES [Company]([Id]),
	
	
)