CREATE TABLE [dbo].[VoucherType]
(
	[Id] INT  NOT NULL, 
    [TypeName] VARCHAR(50) NULL, 
    [Terms] VARCHAR(MAX) NULL, 
	[SendSms] BIT NULL,
    [SmsTemplates] VARCHAR(300) NULL, 
    [SmsToParty] BIT NULL, 
    [SmsToAgent] BIT NULL, 
    [SmsToUser] BIT NULL, 
    [OtherMobile] VARCHAR(100) NULL, 
	[SendMail] BIT NULL,
    [EmailSub] VARCHAR(50) NULL, 
    [EmailBody] VARCHAR(MAX) NULL, 
    [EmailToParty] BIT NULL, 
    [EmailToAgent] BIT NULL, 
    [EmailToUser] BIT NULL, 
    [OtherEmail] VARCHAR(100) NULL,
	[Extra1] VARCHAR(100) NULL, 
    [Extra2] VARCHAR(50) NULL,
	[IsActive] BIT NOT NULL DEFAULT 1, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [CreateDate] DATETIME2 NULL, 
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL, 
    [RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(), 
    CONSTRAINT [PK_VoucherType] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_VoucherType_Id] UNIQUE CLUSTERED ([Id]), 
)
