CREATE TABLE [dbo].[WeftItem]
(
   [Id] INT NOT NULL IDENTITY,
   [ProductId] INT NULL, 
   [TypeId] INT NULL, 
   [Denier] numeric(18,2) NULL,  
   [Qty] numeric(18,3) NULL,
   [PI] numeric(18,2) NULL,
   [RS] numeric(18,2) NULL,
   [RefId] INT NULL, 
   [Remark] VARCHAR(MAX) NULL,
    [Extra1] VARCHAR(100) NULL, 
    [Extra2] VARCHAR(50) NULL,
	[IsActive] BIT NOT NULL DEFAULT 1, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [CreateDate] DATETIME2 NULL, 
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL, 
    [RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(), 
    [AccId] INT NULL, 
    [Ends] NUMERIC(18, 2) NULL, 
    [Mtr] NUMERIC(18, 2) NULL, 
    [ColorId] INT NULL, 
    [MColorId] INT NULL, 
    [VoucherDate] INT NULL, 
    [VDate] DATETIME2 NOT NULL,  
    [ItemId] INT NULL, 
    [Totcard] NUMERIC(18, 2) NOT NULL DEFAULT 0, 
    [TotPick] NUMERIC(18, 2) NOT NULL DEFAULT 0, 
    [Rate] NUMERIC(18, 2) NOT NULL DEFAULT 0, 
    [IType] VARCHAR NULL, 
    [Weight] NUMERIC(18, 3) NOT NULL DEFAULT 0, 
    [Total] NUMERIC(18, 2) NOT NULL DEFAULT 0, 
    [Tar] INT NOT NULL DEFAULT 0, 
    [Costing] NUMERIC(18, 2) NOT NULL DEFAULT 0, 
    [JobCharge] NUMERIC(18, 2) NOT NULL DEFAULT 0, 
    [NWeight] NUMERIC(18, 3) NOT NULL DEFAULT 0, 
    [Wasteper] NUMERIC(18, 3) NOT NULL DEFAULT 0, 
    [Card] NUMERIC(18, 2) NOT NULL DEFAULT 0, 
    [Panno] INT NOT NULL DEFAULT 0, 
    [Change] NUMERIC(18, 2) NULL DEFAULT 0, 
    CONSTRAINT [PK_Weft] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_Weft_Id] UNIQUE CLUSTERED ([Id]),
	CONSTRAINT [FK_Product_weft] FOREIGN KEY ([RefId]) REFERENCES [Product]([Id]) on delete set default

)