CREATE TABLE [dbo].[Attachment]
(
	[Id] INT IDENTITY NOT NULL , 
    [RefVoucherId] INT NULL, 
    [VoucherId] INT NULL, 
    [FilePath] VARCHAR(200) NULL, 
    [FileDescr] VARCHAR(MAX) NULL,
	[FileCatId] INT NULL,
	[FileSubCatId] INT NULL,
	[FileStatus] VARCHAR(50),
	[DeptId] INT NULL,
	[TeamId] INT NULL,
	[PublishDate] DateTIME2 NULL,
	[ExpireDate] Datetime2 NULL,
	[KeyWords] varchar(200),
	[IsActive] BIT NOT NULL DEFAULT 1, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [CreateDate] DATETIME2 NULL, 
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL, 
    [RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(), 
    CONSTRAINT [PK_attachment] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_attachment_Id] UNIQUE CLUSTERED ([Id]), 
)
