CREATE TABLE [dbo].[BillTrans]
(
	[Id] INT IDENTITY NOT NULL , 
    [BillId] INT NULL, 
    [ProductId] INT NULL,
	[HsnCode] VARCHAR(25) NULL, 
    [ColorId] INT NULL, 
    [DesignId] INT NULL, 
    [GradeId] INT NULL, 
	[RefBankId] INT NULL, 
	[ToAccId] INT NULL, 
	[ChequeNo] VARCHAR(50) NULL, 
	[ChequeDate] DATETIME2 NULL, 
	[LotNo] VARCHAR(50) NULL, 
    [AvgWt] NUMERIC(18, 4) NULL DEFAULT 0, 
    [Cut] NUMERIC(10, 2) NULL DEFAULT 0, 
    [Width] NUMERIC(10, 2) NULL DEFAULT 0, 
    [Pcs] INT NULL DEFAULT 0,
    [Qty] NUMERIC(18, 4) NULL DEFAULT 0, 
    [UomId] INT NULL,
	[Rate] Numeric(18,4) NULL ,
	[Total] NUMERIC(18,2) NULL,
	[Disc] NUMERIC(6,2) NULL DEFAULT 0,
	[DiscAmt] NUMERIC(15,2) NULL DEFAULT 0,
	[OceanFrt] numeric(18, 2) NULL DEFAULT 0,
	[CustomD] numeric(18, 2) NULL DEFAULT 0, 
	[FreightRate] NUMERIC(6, 2) NULL DEFAULT 0, 
    [Freight] NUMERIC(18, 2) NULL DEFAULT 0, 
    [OtherAdd] NUMERIC(18, 2) NULL DEFAULT 0, 
    [OtherLess] NUMERIC(18, 2) NULL DEFAULT 0, 
	[SgstPer] NUMERIC(6,2) NULL DEFAULT 0,
	[Sgst] NUMERIC (15,2)  NULL DEFAULT 0,
	[CgstPer] NUMERIC(6,2) NULL DEFAULT 0,
	[Cgst] NUMERIC(15,2) NULL DEFAULT 0,
	[IgstPer] NUMERIC(6,2) NULL DEFAULT 0,
	[Igst] NUMERIC(15,2) NULL DEFAULT 0,
	[CessPer] Numeric(10,2) NULL DEFAULT 0,
	[Cess] Numeric(15,2) NULL DEFAULT 0,
	[TdsPer] NUMERIC(6, 2) NULL DEFAULT 0,
	[TdsAmt] NUMERIC(18, 2) NULL DEFAULT 0, 
	[NetTotal] NUMERIC(18,2) NULL,
    [Remark] VARCHAR(MAX) NULL, 
    [CommDescr] VARCHAR(200) NULL, 
    [DeptId] INT NULL, 
	[DivisionId] INT NULL,
	[RPType] VARCHAR(50),
    [RefId] INT NULL, 
    [RefVoucherId] INT NULL,
	[IsActive] BIT NOT NULL DEFAULT 1,
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [CreateDate] DATETIME2 NULL, 
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL, 
    [RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(), 
    [RefTransId] INT NULL, 
    [TcsPer] NUMERIC(6, 2) NULL DEFAULT 0, 
    [TcsAmt] NUMERIC(18, 2) NULL DEFAULT 0, 
    [BatchId] INT NULL, 
    [BankDate] INT NULL, 
    CONSTRAINT [PK_BillTrans] PRIMARY KEY NONCLUSTERED ([RowId]), 
	CONSTRAINT [AK_BillTrans_Id] UNIQUE CLUSTERED ([Id]), 
    CONSTRAINT [FK_BillTrans_BillMain] FOREIGN KEY ([BillId]) REFERENCES [BillMain]([Id]) ON DELETE CASCADE, 
    CONSTRAINT [FK_BillTrans_Product] FOREIGN KEY ([ProductId]) REFERENCES [Product]([Id]), 


)
