CREATE TABLE [dbo].[BillMain]
(

	[Id] INT IDENTITY NOT NULL,
	[CompId] INT NOT NULL ,
	[YearId] INT NOT NULL,
    [VoucherId] INT NOT NULL, 
	[BookAcId] INT NULL, 
    [VoucherDate] INT NOT NULL, 
    [VoucherNo] VARCHAR(25) NULL,
	[BillNo] VARCHAR(500) NULL,
	[RcdDate] DATETIME2 NULL,
	[Itc] VARCHAR(25) NULL,
	[Rcm] VARCHAR(25) NULL,
	[HasteId] INT NULL,
    [StateId] INT NULL,
    [Duedays] INT NULL,
	[TransId] INT NULL,
	[VehicleNo] VARCHAR(50) NULL,
	[BillType] VARCHAR(50) NULL,
	[DocNo]   VARCHAR(25) NULL,
    [DocDate] DATETIME2 NULL,
	[VDate] DATETIME2 NULL,
    [PortCode] VARCHAR(50) NULL,
    [ModeofTrans] VARCHAR(50) NULL,
    [EwayBillNo]  VARCHAR(50) NULL,
    [RefNo] VARCHAR(25) NULL, 
    [AccId] INT NULL, 
    [EmpId] INT NULL, 
    [StoreId] INT NULL, 
	[DelvAccId] INT NULL,
	[DelvAdrId] INT NULL,
	[DName] VARCHAR(250) NULL,
    [Currency] VARCHAR(50) NULL, 
    [ExchRate] NUMERIC(18, 4) NULL, 
    [AgentId] INT NULL, 
    [BranchId] INT NULL, 
    [RequireDate] DATETIME2 NULL, 
    [DivisionId] INT NULL, 
    [Remarks] VARCHAR(MAX) NULL, 
    [SpecialNotes] VARCHAR(500) NULL, 
    [TotalPcs] NUMERIC(18, 4) DEFAULT 0, 
    [TotalQty] NUMERIC(18, 4) DEFAULT 0, 	
    [TdsPer] NUMERIC(6, 2) DEFAULT 0,
	[TdsAmt] NUMERIC(18, 2) DEFAULT 0,
    [TotalAmount] NUMERIC(18, 2) NOT NULL,
	[GrossAmount] NUMERIC(18, 2) NOT NULL,
	[Extra1] VARCHAR(500) NULL, 
    [Extra2] VARCHAR(500) NULL,
	[Auth] BIT NULL DEFAULT 1,
	[TypeId] INT NULL, 
	[IsActive] BIT NOT NULL DEFAULT 1, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [CreateDate] DATETIME2 NULL, 
	
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL, 
    [RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(), 
    [TcsPer] NUMERIC(6, 2) DEFAULT 0, 
    [TcsAmt] NUMERIC(18, 2) DEFAULT 0, 
    [CustomP] NUMERIC(6, 2) DEFAULT 0, 
    [CustomA] NUMERIC(18, 2) DEFAULT 0, 
    [OceanFrtP] NUMERIC(6, 2) DEFAULT 0, 
    [OceanFrtA] NUMERIC(18, 2) DEFAULT 0, 
    [AddrId] INT NULL, 
    [RoundOff] NUMERIC(6, 2) NULL, 
    [RefId] INT NULL, 
    [RefVoucherId] INT NULL, 
    CONSTRAINT [PK_BillMain] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_BillMain_Id] UNIQUE CLUSTERED ([Id]), 
    CONSTRAINT [FK_BillMain_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [Voucher]([Id]), 
	CONSTRAINT [FK_BillMain_BookAcId] FOREIGN KEY ([BookAcId]) REFERENCES [Acc]([Id]), 
	CONSTRAINT [FK_BillMain_Acc] FOREIGN KEY ([AccId]) REFERENCES [Acc]([Id]), 
    CONSTRAINT [FK_BillMain_Company] FOREIGN KEY ([CompId]) REFERENCES [Company]([Id]), 

)
