CREATE TABLE [dbo].[ChallanTrans]
(
	[Id] INT Identity NOT NULL, 
    [RowId] UNIQUEIDENTIFIER NOT NULL, 
    [ChallanId] INT NULL, 
    [ProductId] INT NULL, 
    [ColorId] INT NULL, 
    [BatchId] INT NULL, 
    [LotNo] VARCHAR(50) NULL, 
    [GradeId] INT NULL, 
    [DesignId] INT NULL, 
    [Cops] NUMERIC(18, 2) NULL, 
    [Pcs] INT NULL, 
    [Qty] NUMERIC(18, 4) NULL, 
	[IssueQty]  NUMERIC(18, 4) NULL, 
    [IssuePcs] NUMERIC(18, 4) NULL, 
	[Rate] NUMERIC(18, 4) NULL, 
    [UomId] INT NULL, 
    [Gross] numeric(18, 2) NULL, 
    [Weight] NUMERIC(18, 2) NULL, 
    [DiscPer] NUMERIC(6, 2) NULL, 
    [Disc] NUMERIC(18, 2) NULL, 
    [FreightRate] NUMERIC(18, 2) NULL, 
    [Freight] NUMERIC(18, 2) NULL, 
    [OtherAdd] NUMERIC(18, 2) NULL, 
    [OtherLess] NUMERIC(18, 2) NULL, 
    [CgstPer] NUMERIC(6, 2) NULL, 
    [Cgst] NUMERIC(18, 2) NULL, 
    [SgstPer] NUMERIC(6, 2) NULL, 
    [Sgst] NUMERIC(18, 2) NULL, 
    [IgstPer] NUMERIC(6, 2) NULL, 
    [Igst] NUMERIC(18, 2) NULL, 
    [Total] NUMERIC(18, 2) NULL, 
    [Remark] VARCHAR(MAX) NULL, 
    [RefId] INT NULL, 
    [RefVoucherId] INT NULL, 
    [MiscId] INT NULL, 
	[IsActive] BIT NOT NULL DEFAULT 1, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [CreateDate] DATETIME2 NULL, 
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL,
	[CessPer] NUMERIC(6, 2) NULL, 
    [Cess] NUMERIC(18, 2) NULL, 
    [NProductId] INT NULL, 
	[RefNo] VARCHAR(50) NULL, 
    CONSTRAINT [PK_ChallanTrans] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_ChallanTrans_Id] UNIQUE CLUSTERED ([Id]) ,
	 CONSTRAINT [FK_CTrans_Ord] FOREIGN KEY ([ChallanId]) REFERENCES [Challan]([Id]) ON DELETE CASCADE, 
    CONSTRAINT [FK_CTrans_Product] FOREIGN KEY ([ProductId]) REFERENCES [Product]([Id]), 
)