CREATE TABLE [dbo].[Challan]
(
	[Id] INT Identity NOT NULL, 
    [RowId] UNIQUEIDENTIFIER NOT NULL, 
    [CompId] INT NULL, 
    [VoucherId] INT NULL, 
    [VoucherNo] VARCHAR(25) NULL, 
    [VoucherDate] INT NULL, 
    [ChallanNo] VARCHAR(25) NULL, 
    [BillNo] VARCHAR(25) NULL, 
    [RcdDate] DATETIME2 NULL, 
    [AccId] INT NULL, 
	[BookAcId] INT NOT NULL DEFAULT(0),
    [AgentId] INT NULL, 
    [DivId] INT NULL, 
    [YearId] INT NULL, 
    [DocNo] VARCHAR(25) NULL, 
    [DocDate] DATETIME2 NULL, 
    [TransId] INT NULL, 
    [Remark] VARCHAR(MAX) NULL, 
    [ChallanType] int NULL, 
    [DelvAccId] INT NULL, 
    [TotalQty] NUMERIC(18, 4) NULL DEFAULT 0, 
    [TotalPcs] NUMERIC(18, 4) NULL DEFAULT 0, 
    [TotalAmount] DECIMAL(18, 2) NULL DEFAULT 0, 
    [BillId] INT NULL, 
    [VehicleNo] VARCHAR(25) NULL, 
	[IsActive] BIT NOT NULL DEFAULT 1, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [CreateDate] DATETIME2 NULL, 
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL, 
    [EmpId] INT NULL, 
    [BranchId] INT NULL, 
    [StoreId] INT NULL,
	[DName] VARCHAR(250) NULL, 
	[DelvAdrId] INT NULL, 
    [TypeId] INT NULL, 
    [AddrId] INT NULL, 
	[BillType] VARCHAR(50) NULL,
	[Itc] VARCHAR(25) NULL,
	[Rcm] VARCHAR(25) NULL,
    [TdsPer] NUMERIC(6, 2) NOT NULL DEFAULT 0,
	[TdsAmt] NUMERIC(18, 2) NOT NULL DEFAULT 0,
    [ProcessId] INT NULL, 
	[RoundOff] NUMERIC(6, 2) NULL, 
    [Extra1] VARCHAR(200) NULL, 
    [Extra2] VARCHAR(200) NULL, 
    [Extra3] VARCHAR(200) NULL, 
	[Extra4] VARCHAR(200) NULL, 
    [MasterId] INT NULL, 
    CONSTRAINT [PK_Challan] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_Challan_Id] UNIQUE CLUSTERED ([Id]) 
)