CREATE TABLE [dbo].[Ord]
(
	[Id] INT IDENTITY NOT NULL,
	[CompId] INT NOT NULL ,
	[YearId] INT NOT NULL,
    [VoucherId] INT NOT NULL, 
    [VoucherDate] INT NOT NULL, 
    [VoucherNo] VARCHAR(25) NULL,
	[OrderStatusId] INT NOT NULL,
    [RefNo] VARCHAR(25) NULL, 
    [AccId] INT NULL, 
    [EmpId] INT NULL, 
	[CheckerId] INT NULL,
	[CheckRate] NUMERIC(15,2) NOT NULL,
	[CheckUomId] INT NULL,
	[CheckerOutId] INT NULL,
	[EmpRate] NUMERIC(15,2) NOT NULL,
	[EmpUomId] INT NULL,
    [StoreId] INT NULL, 
    [Currency] VARCHAR(50) NULL, 
    [ExchRate] NUMERIC(18, 4) NOT NULL, 
    [AgentId] INT NULL, 
    [TransportId] INT NULL, 
    [BranchId] INT NOT NULL, 
    [RequireDate] DATETIME2 NULL, 
    [OrderType] VARCHAR(25) NULL, 
    [DivisionId] INT NOT NULL, 
    [PGroupId] INT NULL, 
    [Remarks] VARCHAR(MAX) NULL, 
    [SpecialNotes] VARCHAR(500) NULL, 
    [PayTermsId] INT NULL, 
    [TotalPcs] NUMERIC(18, 4) NOT NULL, 
    [TotalQty] NUMERIC(18, 4) NULL, 
    [TotalAmount] NUMERIC(18, 2) NOT NULL,
	[Extra1] VARCHAR(50) NULL, 
    [Extra2] VARCHAR(50) NULL,
	[Auth] BIT NOT NULL DEFAULT 1,
	[IsActive] BIT NOT NULL DEFAULT 1, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [CreateDate] DATETIME2 NULL, 
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL, 
    [RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(), 
	  [TypeId] INT NULL, 
    [RefId] INT NULL, 
    [RefVoucherID] INT NULL, 
    CONSTRAINT [PK_ord] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_ord_Id] UNIQUE CLUSTERED ([Id]), 
    CONSTRAINT [FK_Ord_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [Voucher]([Id]), 
	CONSTRAINT [FK_Ord_Acc] FOREIGN KEY ([AccId]) REFERENCES [Acc]([Id]), 
	CONSTRAINT [FK_Ord_Emp] FOREIGN KEY ([EmpId]) REFERENCES [Emp]([Id]), 
    CONSTRAINT [FK_Ord_Company] FOREIGN KEY ([CompId]) REFERENCES [Company]([Id]), 



)
