CREATE TABLE [dbo].[OrdTrans]
(
	[Id] INT IDENTITY NOT NULL , 
    [OrdId] INT NULL, 
    [ProductId] INT NOT NULL, 
    [ColorId] INT NOT NULL, 
    [DesignId] INT NOT NULL, 
    [GradeId] INT NULL, 
    [AvgWt] NUMERIC(18, 4) NOT NULL, 
    [Cut] NUMERIC(10, 2) NOT NULL, 
    [Width] NUMERIC(10, 2) NOT NULL, 
	[NoOfLot] INT NOT NULL, 
    [LotPcs] INT NOT NULL,
    [Qty] NUMERIC(18, 4) NOT NULL, 
    [UomId] INT NOT NULL,
	[Rate] Numeric(18,4) NOT NULL,
	[Total] NUMERIC(18,2) NOT NULL,
	[Disc] NUMERIC(6,2) NOT NULL,
	[DiscAmt] NUMERIC(15,2) NOT NULL,
	[Sgst] NUMERIC(6,2) NOT NULL,
	[SgstAmt] NUMERIC (15,2) NOT NULL,
	[Cgst] NUMERIC(6,2) NOT NULL,
	[CgstAmt] NUMERIC(15,2) NOT NULL,
	[Igst] NUMERIC(6,2) NOT NULL,
	[IgstAmt] NUMERIC(15,2) NOT NULL,
	[Cess] Numeric(10,2) NOT NULL,
	[CessAmt] Numeric(15,2) NOT NULL,
	[NetTotal] NUMERIC(18,2) NOT NULL,
    [Remark] VARCHAR(200) NULL, 
    [CommDescr] VARCHAR(200) NULL, 
    [DeptId] INT NOT NULL, 
	[DivisionId] INT NOT NULL,
	[Priority] VARCHAR(10) NULL,
	[OrdStatus] VARCHAR(25),
    [RefId] INT NULL, 
    [RefVoucherId] INT NULL,
	[CancelReason] VARCHAR(200),
	[IsActive] BIT NOT NULL DEFAULT 1,
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [CreateDate] DATETIME2 NULL, 
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL, 
    [RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(), 
    [WarpItemId] INT NULL, 
    CONSTRAINT [PK_OrdTrans] PRIMARY KEY NONCLUSTERED ([RowId]), 
	CONSTRAINT [AK_OrdTrans_Id] UNIQUE CLUSTERED ([Id]), 
    CONSTRAINT [FK_OrdTrans_Ord] FOREIGN KEY ([OrdId]) REFERENCES [Ord]([Id]) ON DELETE CASCADE, 
    CONSTRAINT [FK_OrdTrans_Product] FOREIGN KEY ([ProductId]) REFERENCES [Product]([Id]), 


)
