CREATE TABLE [dbo].[Prod]
(
	[Id] INT NOT NULL IDENTITY ,  
    [RowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NewSequentialid(), 
    [TransId] INT NULL, 
    [SrNo] INT NULL, 
    [ProductId] INT NULL, 
    [GradeId] INT NULL, 
    [ColorId] INT NULL, 
    [PackId] INT NULL, 
    [MacId] INT NULL, 
    [SubGradeId] INT NULL, 
    [TwistType] VARCHAR(50) NULL, 
    [CompId] INT NULL, 
    [YearId] INT NULL, 
    [VoucherId] INT NULL, 
    [VoucherDate] INT NULL, 
    [VoucherNo] VARCHAR(25) NULL, 
    [RefId] INT NULL, 
    [RefSCId] INT NULL, 
    [Ply] INT NULL, 
    [Cops] INT NULL, 
    [CopsWt] NUMERIC(18, 4) NULL DEFAULT 0, 
    [BoxWt] NUMERIC(18, 4) NULL DEFAULT 0, 
    [CartnWt] NUMERIC(18, 4) NULL DEFAULT 0, 
    [GrossWt] NUMERIC(18, 4) NULL DEFAULT 0, 
    [TareWt] NUMERIC(18, 4) NULL DEFAULT 0, 
    [NetWt] NUMERIC(18, 4) NULL DEFAULT 0, 
    [DivId] INT NULL, 
    [BranchId] INT NULL, 
    [JobId] INT NULL, 
    [CopsProductId] INT NULL, 
    [CopsRate] NUMERIC(10, 3) NULL DEFAULT 0, 
    [BoxProductId] INT NULL, 
    [BoxRate] NUMERIC(10, 3) NULL DEFAULT 0, 
    [PackEmpId] INT NULL, 
    [CheckEmpId] INT NULL, 
    [PalletProductId] INT NULL, 
    [PlyProductId] INT NULL, 
    [DrawingDate] DATETIME2 NULL, 
	[WarpingDate] DATETIME2 NULL, 
	[CloseDate] DATETIME2 NULL, 
	[LoadingDate] DATETIME2 NULL, 
    [ProdStatus] NVARCHAR(50) NULL, 
    [Tops] INT NULL DEFAULT 0, 
    [Pallet] INT NULL DEFAULT 0, 
    [CurrQty] NUMERIC(18, 4) NULL DEFAULT 0, 
    [FinQty] NUMERIC(18, 4) NULL DEFAULT 0, 
    [IssueRefId] INT NULL, 
    [IssueRefVoucherId] INT NULL, 
    [Remark] NVARCHAR(MAX) NULL, 
	[IsActive] BIT NOT NULL DEFAULT 1, 
	[IsClose] BIT NOT NULL DEFAULT 0, 
	[IsMultiple] BIT NOT NULL DEFAULT 0, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [CreateDate] DATETIME2 NULL, 
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL, 
    [BatchId] INT NULL,  
	[RefIssueId] INT NULL,  
	[IsOk] bit null default 1,
	 
    [VTypeId] INT NOT NULL DEFAULT 0, 
    [LotNo] VARCHAR(50) NULL, 
    [Extra1] VARCHAR(200) NULL, 
    CONSTRAINT [PK_Prod] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_Prod_Id] UNIQUE CLUSTERED ([Id]) ,
	 CONSTRAINT [FK_prod_trans] FOREIGN KEY ([TransId]) REFERENCES [ChallanTrans]([Id]),  
	 CONSTRAINT [FK_prod_Challan] FOREIGN KEY ([RefId]) REFERENCES [Challan]([Id]),  
	 CONSTRAINT [FK_prod_Product] FOREIGN KEY ([ProductId]) REFERENCES [Product]([Id]), 
	 CONSTRAINT [FK_prod_Color] FOREIGN KEY ([ColorId]) REFERENCES [Color]([Id])
)