CREATE TABLE [dbo].[StockTrans]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CompanyId] [smallint] NOT NULL,
	[BranchId] [int] NOT NULL,
	[YearId] [int] NOT NULL,
	[GodownId] [int] NOT NULL,
	[RefId] [uniqueidentifier] NOT NULL,
	[MasterRefId] [uniqueidentifier] NULL,
	[VoucherDate] [int] NOT NULL,
	[TransDate] [datetime] NULL,
	[VoucherId] [int] NOT NULL,
	[BillNo] [varchar](25) NULL,
	[VoucherNo] [varchar](25) NULL,
	[AccountId] [int] NULL,
	[ItemId] [int] NOT NULL,
	[RcptNos] [int] NOT NULL,
	[RcptQty] [numeric](18, 3) NOT NULL,
	[IssueNos] [int] NOT NULL,
	[IssueQty] [numeric](18, 3) NOT NULL,
	[Rate] [numeric](18, 3) NOT NULL,
	[Amount] [numeric](18, 2) NOT NULL,
	[AgentId] [int] NOT NULL,
	[TableName] [varchar](25) NULL,
	[KeyFldValue] [int] NULL,
	[Narration] [varchar](max) NULL,
	[TransDateTime] [datetime2](7) NULL,
	[Qty] [numeric](18, 4) NULL,
	[IsActive] [Bit] NULL,
	[IsDeleted] [Bit] NULL,
    [RowId] UNIQUEIDENTIFIER NOT NULL , 
    [ColorId] INT NULL, 
    [BatchId] INT NULL, 
    [GradeId] INT NULL, 
	[DesignId] INT NULL,
	[ChallanType] INT NULL,
    [DivId] INT NULL, 
    [LotNo] VARCHAR(50) NULL, 
    [Cut] NUMERIC(18, 2) NULL, 
    [Pcs] INT NULL, 
	[UomId] INT NULL,
	[CreateDate] DATETIME2 NULL, 
    [ModifyDate] DATETIME2 NULL, 
    [CreateUser] VARCHAR(50) NULL, 
    [ModifyUser] VARCHAR(50) NULL, 
    [IpAddress] VARCHAR(100) NULL, 
    CONSTRAINT [PK_StockTrans] PRIMARY KEY NONCLUSTERED ([RowId]), 
    CONSTRAINT [AK_StockTrans_Id] UNIQUE CLUSTERED ([Id]), 
)
GO

CREATE INDEX [IX_StockTrans_MasterRefId] ON [dbo].[StockTrans] ([MasterRefId])
